repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
    exclude: template.yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: WHEEL
    exclude_types: [json]
  - id: forbid-new-submodules
  - id: trailing-whitespace
    exclude: .patch
    exclude_types: [json]

- repo: local
  hooks:
    - id: synchro
      name: synchro
      entry: bash ./tools/synchro.sh
      language: python
      require_serial: true
      additional_dependencies:
        - ruff==0.1.3
        - unasync

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.3
  hooks:
    - id: ruff
      args: ["--fix", "--show-fixes"]
    - id: ruff-format

- repo: https://github.com/adamchainz/blacken-docs
  rev: "1.16.0"
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black==22.3.0

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: "v1.10.0"
  hooks:
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal

# We use the Python version instead of the original version which seems to require Docker
# https://github.com/koalaman/shellcheck-precommit
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.6
  hooks:
    - id: shellcheck
      name: shellcheck
      args: ["--severity=warning"]
      stages: [manual]

- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.29.0
  hooks:
    - id: check-github-workflows
    - id: check-github-actions
    - id: check-jsonschema
      files: .*/(database|indexes)/.json$

- repo: https://github.com/codespell-project/codespell
  rev: "v2.2.6"
  hooks:
  - id: codespell